name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]

jobs:
  bun-testing-UNIX:
    runs-on: ubuntu-latest
    steps:
      - name: Getting checkout
        uses: actions/checkout@v6
      - name: Getting BUN
        uses: oven-sh/setup-bun@v2
      - name: Download Project Dependency
        run: bun install
      - name: Testing in UNIX
        run: bun test

  bun-testing-WIN:
    runs-on: windows-latest
    steps:
      - name: Getting checkout
        uses: actions/checkout@v6
      - name: Getting BUN
        uses: oven-sh/setup-bun@v2
      - name: Download Project Dependency
        run: bun install
      - name: Testing in Windows
        run: bun test
